-- WARNING: This schema is for context only and is not meant to be run.
-- Table order and constraints may not be valid for execution.

CREATE TABLE public.analyses (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  submission_id uuid NOT NULL,
  enrichment_id uuid NOT NULL,
  swot jsonb,
  pestel jsonb,
  porter jsonb,
  okrs jsonb,
  synthesis jsonb,
  status character varying NOT NULL DEFAULT 'pending'::character varying CHECK (status::text = ANY (ARRAY['pending'::character varying, 'processing'::character varying, 'completed'::character varying, 'approved'::character varying, 'sent'::character varying, 'failed'::character varying]::text[])),
  error_message text,
  processing_time_ms bigint,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  completed_at timestamp with time zone,
  tam_sam_som jsonb,
  benchmarking jsonb,
  blue_ocean jsonb,
  growth_hacking jsonb,
  scenarios jsonb,
  bsc jsonb,
  decision_matrix jsonb,
  version integer NOT NULL DEFAULT 1,
  parent_analysis_id uuid,
  is_latest boolean NOT NULL DEFAULT true,
  approved_at timestamp with time zone,
  approved_by uuid,
  sent_at timestamp with time zone,
  sent_to character varying,
  deleted_at timestamp with time zone,
  CONSTRAINT analyses_pkey PRIMARY KEY (id),
  CONSTRAINT analyses_submission_id_fkey FOREIGN KEY (submission_id) REFERENCES public.submissions(id),
  CONSTRAINT analyses_enrichment_id_fkey FOREIGN KEY (enrichment_id) REFERENCES public.enrichments(id),
  CONSTRAINT fk_parent_analysis FOREIGN KEY (parent_analysis_id) REFERENCES public.analyses(id)
);
CREATE TABLE public.enrichments (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  submission_id uuid NOT NULL,
  status character varying NOT NULL DEFAULT 'pending'::character varying CHECK (status::text = ANY (ARRAY['pending'::character varying, 'completed'::character varying, 'approved'::character varying]::text[])),
  progress integer NOT NULL DEFAULT 0 CHECK (progress >= 0 AND progress <= 100),
  current_step text,
  sources_status jsonb,
  sources_used ARRAY,
  enrichment_score numeric CHECK (enrichment_score IS NULL OR enrichment_score >= 0::numeric AND enrichment_score <= 100::numeric),
  error_message text,
  retry_count integer NOT NULL DEFAULT 0,
  max_retries integer NOT NULL DEFAULT 3,
  processing_time_ms bigint,
  started_at timestamp with time zone,
  completed_at timestamp with time zone,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  is_locked boolean DEFAULT false,
  approved_at timestamp with time zone,
  approved_by uuid,
  data jsonb DEFAULT '{}'::jsonb,
  CONSTRAINT enrichments_pkey PRIMARY KEY (id),
  CONSTRAINT enrichments_submission_id_fkey FOREIGN KEY (submission_id) REFERENCES public.submissions(id)
);
CREATE TABLE public.reports (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  submission_id uuid NOT NULL,
  analysis_id uuid NOT NULL,
  cover_page text,
  executive_summary text,
  table_of_contents text,
  swot_page text,
  pestel_page text,
  porter_page text,
  okr_page text,
  strategic_priorities_page text,
  risks_mitigation_page text,
  appendix_page text,
  pdf_url character varying,
  pdf_generated_at timestamp with time zone,
  pdf_generation_status character varying NOT NULL DEFAULT 'pending'::character varying CHECK (pdf_generation_status::text = ANY (ARRAY['pending'::character varying, 'processing'::character varying, 'completed'::character varying, 'failed'::character varying]::text[])),
  status character varying NOT NULL DEFAULT 'pending'::character varying CHECK (status::text = ANY (ARRAY['pending'::character varying, 'processing'::character varying, 'completed'::character varying, 'failed'::character varying]::text[])),
  error_message text,
  generation_time_ms bigint,
  total_pages integer NOT NULL DEFAULT 24,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  completed_at timestamp with time zone,
  tam_sam_som_page text,
  benchmarking_page text,
  blue_ocean_page text,
  growth_hacking_page text,
  scenarios_page text,
  bsc_page text,
  decision_matrix_page text,
  divider_part1_page text,
  pestel_pes_page text,
  pestel_tel_page text,
  divider_part2_page text,
  divider_part3_page text,
  growth_loops_page text,
  divider_part4_page text,
  recommendations_page text,
  roadmap_page text,
  CONSTRAINT reports_pkey PRIMARY KEY (id),
  CONSTRAINT reports_submission_id_fkey FOREIGN KEY (submission_id) REFERENCES public.submissions(id),
  CONSTRAINT reports_analysis_id_fkey FOREIGN KEY (analysis_id) REFERENCES public.analyses(id)
);
CREATE TABLE public.submissions (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  company_name character varying NOT NULL,
  company_website character varying,
  company_industry character varying,
  company_size character varying,
  company_location character varying,
  contact_name character varying NOT NULL,
  contact_email character varying NOT NULL,
  contact_phone character varying,
  contact_position character varying,
  target_market text,
  annual_revenue_min numeric,
  annual_revenue_max numeric,
  funding_stage character varying,
  business_challenge text NOT NULL,
  additional_notes text,
  linkedin_url character varying,
  twitter_handle character varying,
  status character varying NOT NULL DEFAULT 'received'::character varying CHECK (status::text = 'received'::text),
  user_id uuid,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  deleted_at timestamp with time zone,
  CONSTRAINT submissions_pkey PRIMARY KEY (id),
  CONSTRAINT fk_submissions_user FOREIGN KEY (user_id) REFERENCES public.user_profiles(id)
);
CREATE TABLE public.user_profiles (
  id uuid NOT NULL,
  email character varying NOT NULL,
  full_name character varying,
  avatar_url text,
  role USER-DEFINED NOT NULL DEFAULT 'user'::user_role,
  is_active boolean DEFAULT true,
  organization_name character varying,
  job_title character varying,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT user_profiles_pkey PRIMARY KEY (id),
  CONSTRAINT user_profiles_id_fkey FOREIGN KEY (id) REFERENCES auth.users(id)
);