-- ==================== MIGRATION 005: Fix Framework Mismatch ====================
-- This migration aligns the database schema with the new Strategic Cascade framework
-- implemented in workflow.go and model.go.
--
-- CHANGES:
-- Removes: BCG Matrix, Value Proposition Canvas, Business Model Canvas (3 old frameworks)
-- Adds: TAM-SAM-SOM, Benchmarking, Blue Ocean, Growth Hacking, Scenarios, BSC, Decision Matrix (7 new frameworks)
--
-- Author: Migration System
-- Date: 2025-11-21
-- ==================================================================================

-- ==================== 1. UPDATE ANALYSES TABLE ====================

-- Remove old framework columns
ALTER TABLE analyses
  DROP COLUMN IF EXISTS bcg_matrix,
  DROP COLUMN IF EXISTS value_proposition,
  DROP COLUMN IF EXISTS business_model;

-- Add new framework columns defined in workflow.go / model.go
-- All frameworks are stored as JSONB for flexible structured data
ALTER TABLE analyses
  ADD COLUMN IF NOT EXISTS tam_sam_som JSONB,
  ADD COLUMN IF NOT EXISTS benchmarking JSONB,
  ADD COLUMN IF NOT EXISTS blue_ocean JSONB,
  ADD COLUMN IF NOT EXISTS growth_hacking JSONB,
  ADD COLUMN IF NOT EXISTS scenarios JSONB,
  ADD COLUMN IF NOT EXISTS bsc JSONB,
  ADD COLUMN IF NOT EXISTS decision_matrix JSONB;

-- Add comments for documentation
COMMENT ON COLUMN analyses.tam_sam_som IS 'TAM-SAM-SOM market size analysis (Layer 1: Environment)';
COMMENT ON COLUMN analyses.benchmarking IS 'Competitive benchmarking analysis (Layer 2: Positioning)';
COMMENT ON COLUMN analyses.blue_ocean IS 'Blue Ocean strategy analysis (Layer 3: Strategy)';
COMMENT ON COLUMN analyses.growth_hacking IS 'Growth hacking framework analysis (Layer 3: Strategy)';
COMMENT ON COLUMN analyses.scenarios IS 'Scenario planning analysis (Layer 3: Strategy)';
COMMENT ON COLUMN analyses.bsc IS 'Balanced Scorecard analysis (Layer 4: Execution)';
COMMENT ON COLUMN analyses.decision_matrix IS 'Decision matrix analysis (Layer 4: Execution)';

-- ==================== 2. UPDATE REPORTS TABLE ====================

-- Remove old framework report pages
ALTER TABLE reports
  DROP COLUMN IF EXISTS bcg_matrix_page,
  DROP COLUMN IF EXISTS value_proposition_page,
  DROP COLUMN IF EXISTS business_model_page;

-- Add new framework report pages
-- Each page stores the rendered HTML for that framework section
ALTER TABLE reports
  ADD COLUMN IF NOT EXISTS tam_sam_som_page TEXT,
  ADD COLUMN IF NOT EXISTS benchmarking_page TEXT,
  ADD COLUMN IF NOT EXISTS blue_ocean_page TEXT,
  ADD COLUMN IF NOT EXISTS growth_hacking_page TEXT,
  ADD COLUMN IF NOT EXISTS scenarios_page TEXT,
  ADD COLUMN IF NOT EXISTS bsc_page TEXT,
  ADD COLUMN IF NOT EXISTS decision_matrix_page TEXT;

-- Add comments for documentation
COMMENT ON COLUMN reports.tam_sam_som_page IS 'Rendered HTML page for TAM-SAM-SOM analysis';
COMMENT ON COLUMN reports.benchmarking_page IS 'Rendered HTML page for benchmarking analysis';
COMMENT ON COLUMN reports.blue_ocean_page IS 'Rendered HTML page for Blue Ocean strategy';
COMMENT ON COLUMN reports.growth_hacking_page IS 'Rendered HTML page for growth hacking framework';
COMMENT ON COLUMN reports.scenarios_page IS 'Rendered HTML page for scenario planning';
COMMENT ON COLUMN reports.bsc_page IS 'Rendered HTML page for Balanced Scorecard';
COMMENT ON COLUMN reports.decision_matrix_page IS 'Rendered HTML page for decision matrix';

-- ==================== 3. MIGRATION NOTES ====================
/*
STRATEGIC CASCADE FRAMEWORK (4 Layers):

Layer 1: Environment
  - PESTEL (external macro environment)
  - Porter (industry structure and competition)
  - TAM-SAM-SOM (market sizing)

Layer 2: Positioning
  - SWOT (internal/external factors)
  - Benchmarking (competitive positioning)

Layer 3: Strategy
  - Blue Ocean (create new market space)
  - Growth Hacking (rapid scaling tactics)
  - Scenarios (strategic options)

Layer 4: Execution
  - OKRs (objectives and key results)
  - BSC (balanced scorecard)
  - Decision Matrix (prioritization)

DATA MIGRATION:
No data migration is required as:
1. New columns are nullable JSONB (allow NULL values)
2. Old columns being dropped contained outdated framework data
3. New framework data will be generated by the updated workflow.go logic
4. Existing data in SWOT, PESTEL, Porter, OKRs remains unchanged

ROLLBACK:
To rollback this migration, reverse the operations:
- DROP the 7 new columns
- ADD back the 3 old columns
- Update repository.go to use old column names
*/
