-- ==================== MIGRATION 006: Fix Reports Framework Mismatch ====================
-- This migration aligns the reports table with the new Strategic Cascade framework
-- and fixes the critical Service → Model → Repository mismatch.
--
-- ISSUE:
-- - Service (service.go) generates 16 HTML pages
-- - Model (model.go) only has 13 page fields (with OLD framework names)
-- - Repository (repository.go) only stores 13 columns
-- - Service fails to assign generated HTML to Report struct (CRITICAL BUG)
--
-- CHANGES:
-- - ADD 7 new page columns for new frameworks
-- - RENAME business_model_page → bsc_page (Balanced Scorecard)
-- - KEEP old columns for backward compatibility (marked as deprecated)
-- - UPDATE table comment from "13 pages" to "16 pages"
--
-- Author: Migration System
-- Date: 2025-11-21
-- ==================================================================================

-- ==================== 1. ADD NEW FRAMEWORK PAGE COLUMNS ====================

ALTER TABLE reports
  ADD COLUMN IF NOT EXISTS tam_sam_som_page TEXT,
  ADD COLUMN IF NOT EXISTS blue_ocean_page TEXT,
  ADD COLUMN IF NOT EXISTS benchmarking_page TEXT,
  ADD COLUMN IF NOT EXISTS financial_projections_page TEXT,
  ADD COLUMN IF NOT EXISTS growth_hacking_page TEXT,
  ADD COLUMN IF NOT EXISTS risk_assessment_page TEXT,
  ADD COLUMN IF NOT EXISTS decision_matrix_page TEXT;

-- Add documentation comments
COMMENT ON COLUMN reports.tam_sam_som_page IS 'TAM-SAM-SOM market sizing page HTML (Page 7)';
COMMENT ON COLUMN reports.blue_ocean_page IS 'Blue Ocean strategy page HTML (Page 8)';
COMMENT ON COLUMN reports.benchmarking_page IS 'Competitive benchmarking/analysis page HTML (Page 11)';
COMMENT ON COLUMN reports.financial_projections_page IS 'Financial projections/scenarios page HTML (Page 12)';
COMMENT ON COLUMN reports.growth_hacking_page IS 'Growth hacking/GTM strategy page HTML (Page 13)';
COMMENT ON COLUMN reports.risk_assessment_page IS 'Risk assessment page HTML (Page 14)';
COMMENT ON COLUMN reports.decision_matrix_page IS 'Decision matrix/roadmap page HTML (Page 15)';

-- ==================== 2. RENAME BUSINESS MODEL PAGE TO BSC ====================

-- Rename the column to reflect actual content (Balanced Scorecard)
ALTER TABLE reports
  RENAME COLUMN business_model_page TO bsc_page;

-- Update comment
COMMENT ON COLUMN reports.bsc_page IS 'Balanced Scorecard (BSC) page HTML (Page 10) - Previously business_model_page';

-- ==================== 3. MARK OLD COLUMNS AS DEPRECATED ====================

-- These columns are kept for backward compatibility but are no longer populated by the service
COMMENT ON COLUMN reports.bcg_matrix_page IS 'DEPRECATED: BCG Matrix page (no longer generated by service) - kept for backward compatibility';
COMMENT ON COLUMN reports.value_proposition_page IS 'DEPRECATED: Value Proposition Canvas page (no longer generated) - kept for backward compatibility';
COMMENT ON COLUMN reports.strategic_priorities_page IS 'DEPRECATED: Strategic Priorities page (no longer generated) - kept for backward compatibility';
COMMENT ON COLUMN reports.risks_mitigation_page IS 'DEPRECATED: Old risks/mitigation page (replaced by risk_assessment_page) - kept for backward compatibility';

-- ==================== 4. UPDATE TABLE COMMENT ====================

COMMENT ON TABLE reports IS 'Generated business analysis reports with 16 pages of strategic frameworks and a compiled PDF (updated from 13 pages)';

-- ==================== 5. MIGRATION NOTES ====================
/*
NEW REPORT STRUCTURE (16 Pages):

Page 1:  Cover Page (cover_page)
Page 2:  Executive Summary (executive_summary)
Page 3:  Table of Contents (table_of_contents)
Page 4:  PESTEL Analysis (pestel_page)
Page 5:  Porter's Five Forces (porter_page)
Page 6:  SWOT Analysis (swot_page)
Page 7:  TAM-SAM-SOM Market Sizing (tam_sam_som_page) ✨ NEW
Page 8:  Blue Ocean Strategy (blue_ocean_page) ✨ NEW
Page 9:  OKRs (okr_page)
Page 10: Balanced Scorecard (bsc_page) 🔄 RENAMED from business_model_page
Page 11: Competitive Benchmarking (benchmarking_page) ✨ NEW
Page 12: Financial Projections (financial_projections_page) ✨ NEW
Page 13: Growth Hacking / GTM Strategy (growth_hacking_page) ✨ NEW
Page 14: Risk Assessment (risk_assessment_page) ✨ NEW
Page 15: Decision Matrix / Roadmap (decision_matrix_page) ✨ NEW
Page 16: Appendix (appendix_page)

STRATEGIC CASCADE LAYERS:
Layer 1 (Environment): PESTEL, Porter, TAM-SAM-SOM
Layer 2 (Positioning): SWOT, Benchmarking
Layer 3 (Strategy): Blue Ocean, Growth Hacking, Scenarios
Layer 4 (Execution): OKRs, BSC, Decision Matrix

DEPRECATED PAGES (kept for backward compatibility):
- bcg_matrix_page (old BCG Matrix framework)
- value_proposition_page (old Value Proposition Canvas)
- strategic_priorities_page (old Strategic Priorities)
- risks_mitigation_page (old Risks/Mitigation - different from new risk_assessment_page)

SERVICE BUG FIX REQUIRED:
After running this migration, you MUST update domain/report/service.go (lines 185-197)
to assign the generated HTML pages to the Report struct fields before saving.
Currently, the service generates 16 HTML pages but discards them and saves an empty Report.

DATA MIGRATION:
No data migration is required as:
1. New columns are nullable TEXT (allow NULL values)
2. Old deprecated columns remain in place with existing data
3. New reports will populate all 16 page fields once service.go is fixed
4. Column rename (business_model_page → bsc_page) preserves existing data

ROLLBACK:
To rollback this migration:
- DROP the 7 new columns
- RENAME bsc_page back to business_model_page
- Revert comments on deprecated columns
- Update table comment back to "13 pages"
*/
