-- v2_017_enrichment_v3_fields.sql
-- Add additional enrichment fields from Perplexity + Claude pipeline

-- Products & Services
ALTER TABLE companies ADD COLUMN IF NOT EXISTS main_products jsonb DEFAULT '[]';
ALTER TABLE companies ADD COLUMN IF NOT EXISTS customer_segments jsonb DEFAULT '[]';
ALTER TABLE companies ADD COLUMN IF NOT EXISTS pricing_model text;
ALTER TABLE companies ADD COLUMN IF NOT EXISTS unique_selling_points jsonb DEFAULT '[]';

-- News & Leadership
ALTER TABLE companies ADD COLUMN IF NOT EXISTS recent_news jsonb DEFAULT '[]';
ALTER TABLE companies ADD COLUMN IF NOT EXISTS key_executives jsonb DEFAULT '[]';
ALTER TABLE companies ADD COLUMN IF NOT EXISTS company_history text;

-- SWOT Extended (O&T generated by analysis, but stored from enrichment too)
ALTER TABLE companies ADD COLUMN IF NOT EXISTS opportunities jsonb DEFAULT '[]';
ALTER TABLE companies ADD COLUMN IF NOT EXISTS threats jsonb DEFAULT '[]';
ALTER TABLE companies ADD COLUMN IF NOT EXISTS strategic_challenges jsonb DEFAULT '[]';

-- Competitive Intelligence
ALTER TABLE companies ADD COLUMN IF NOT EXISTS competitor_details jsonb DEFAULT '[]';
ALTER TABLE companies ADD COLUMN IF NOT EXISTS competitive_advantage text;
ALTER TABLE companies ADD COLUMN IF NOT EXISTS market_share text;

-- Market Sizing (enrichment estimates, analysis generates fresh)
ALTER TABLE companies ADD COLUMN IF NOT EXISTS tam_estimate text;
ALTER TABLE companies ADD COLUMN IF NOT EXISTS sam_estimate text;
ALTER TABLE companies ADD COLUMN IF NOT EXISTS som_estimate text;

-- Add comments for documentation
COMMENT ON COLUMN companies.main_products IS 'Key products/services from enrichment';
COMMENT ON COLUMN companies.recent_news IS 'Recent news headlines from web search';
COMMENT ON COLUMN companies.key_executives IS 'CEO, CTO, etc. with roles';
COMMENT ON COLUMN companies.opportunities IS 'Market opportunities from enrichment';
COMMENT ON COLUMN companies.threats IS 'External threats from enrichment';
COMMENT ON COLUMN companies.tam_estimate IS 'Total Addressable Market estimate from enrichment';
COMMENT ON COLUMN companies.sam_estimate IS 'Serviceable Addressable Market estimate';
COMMENT ON COLUMN companies.som_estimate IS 'Serviceable Obtainable Market estimate';
